name: tennis_scheduler
description: "Proyecto gestion profes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^7.6.7
  injectable: ^2.4.4
  firebase_core: ^4.15.0
  firebase_auth: 6.7.0
  cloud_firestore: ^6.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true