// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ICvsuPT0S2rrpKL00RMX8dYYzmogmW8',
    appId: '1:878515941599:web:da334e1e776a249defb96a',
    messagingSenderId: '878515941599',
    projectId: 'tennis-schedulle',
    authDomain: 'tennis-schedulle.firebaseapp.com',
    storageBucket: 'tennis-schedulle.firebasestorage.app',
    measurementId: 'G-JP26EY7X8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5rsHJwLZxRdXb6f863qbODyTllda8VRA',
    appId: '1:878515941599:android:c9c6238654ccf8e6efb96a',
    messagingSenderId: '878515941599',
    projectId: 'tennis-schedulle',
    storageBucket: 'tennis-schedulle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQTKTfm8xkMib2QqRnt65XHwbePlF3bpg',
    appId: '1:878515941599:ios:f5d01f0bbf378e6cefb96a',
    messagingSenderId: '878515941599',
    projectId: 'tennis-schedulle',
    storageBucket: 'tennis-schedulle.firebasestorage.app',
    iosBundleId: 'com.tennis.tennisScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQTKTfm8xkMib2QqRnt65XHwbePlF3bpg',
    appId: '1:878515941599:ios:f5d01f0bbf378e6cefb96a',
    messagingSenderId: '878515941599',
    projectId: 'tennis-schedulle',
    storageBucket: 'tennis-schedulle.firebasestorage.app',
    iosBundleId: 'com.tennis.tennisScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ICvsuPT0S2rrpKL00RMX8dYYzmogmW8',
    appId: '1:878515941599:web:7d64b83078c5ee16efb96a',
    messagingSenderId: '878515941599',
    projectId: 'tennis-schedulle',
    authDomain: 'tennis-schedulle.firebaseapp.com',
    storageBucket: 'tennis-schedulle.firebasestorage.app',
    measurementId: 'G-0QLJX49Y6F',
  );
}
